export const FETCH_POCKEMONES_REQUEST = 'POCKEMONES.FETCH_REQUEST';
export const FETCH_POCKEMONES_FAILURE = 'POCKEMONES.FETCH_FAILURE';
export const FETCH_POCKEMONES_SUCCESS = 'POCKEMONES.FETCH_SUCCESS';
