export const generateTableConfig = options => {
  const {
    isLoading,
    isLoaded,
    isHighlightUpdateButton,
    isShowDatepicker,
  } = options;
  const WebkitFontSmoothing = window.devicePixelRatio > 1 ? 'antialiased' : 'inherit';

  let animationButton;
  if (isHighlightUpdateButton) {
    animationButton = 'pulse 1s infinite';
  } else {
    animationButton = isLoading ? 'pulse 0.5s infinite' : 'none';
  }

  return {
    containerStyle:           {
      backgroundColor: isLoading ? '#ccc' : '#fff',
      paddingBottom:   0,
    },
    titleRowStyle:            {
      height:           isLoading || !isLoaded ? 2 : 50,
      backgroundColor:  '#1ba6d2',
      color:            'white',
      WebkitTransition: 'height 1s',
      transition:       'height 1s',
    },
    titleStyle:               {
      WebkitFontSmoothing,
      fontSize:         isLoading || !isLoaded ? 0 : 36,
      textAlign:        'center',
      marginTop:        12,
      WebkitTransition: 'font-size 1s',
      transition:       'font-size 1s',
    },
    headerRowStyle:           {
      backgroundColor: '#1ba6d2',
      color:           'white',
      height:          40,
      h1:              {
        position:      'absolute',
        left:          30,
        top:           15,
        textTransform: 'uppercase',
        fontSize:      17,
      },
    },
    maxWidthCenteredStyle:    {
      width:     '100%',
      textAlign: 'center',
      padding:   '0 0 5px 0',
    },
    controlWrapStyle:         {
      height:   40,
      width:    200,
      overflow: 'visible',
      position: 'relative',
      display:  'inline-block',
      margin:   '0 10px 0 10px',
    },
    controlWrapStyle2:        {
      display:  'inline-block',
      position: 'relative',
      width:    200,
      height:   40,
    },
    controlWrapStyle3:        {
      display:     'inline-block',
      float:       'right',
      position:    'relative',
      height:      40,
      marginRight: 40,
    },
    chartWrapper:             {
      visibility: 'visible',
    },
    paginationOverlayLoading: {
      display:     'none',
      marginLeft:  'auto',
      marginRight: 'auto',
      position:    'relative',
      top:         -34,
      zIndex:      100,
      fontSize:    14,
    },
    paginationGoTo:           {
      width:       160,
      marginLeft:  'auto',
      marginRight: 'auto',
      position:    'relative',
      top:         -40,
      zIndex:      100,
    },
    paginationGoToLabel:      {
      fontSize:   14,
      display:    'inline-block',
      width:      200,
      whiteSpace: 'no-wrap',
    },
    paginationGoToInput:      {
      fontSize: 14,
      display:  'inline',
      width:    60,
    },
    tableRow:                 {
      visibility: isLoaded ? 'visible' : 'hidden',
      position:   'relative',
      padding:    '0 50px',
    },
    hideDataPicker:           {
      display:  isShowDatepicker ? 'block' : 'none',
      position: 'fixed',
      top:      0,
      left:     0,
      bottom:   0,
      right:    0,
      zIndex:   99998,
    },
    rangeStyle:               {
      position:         'absolute',
      top:              2,
      left:             0,
      right:            0,
      border:           'none',
      backgroundColor:  'transparent',
      color:            '#fff',
      fontSize:         12,
      letterSpacing:    1,
      textTransform:    'uppercase',
      fontWeight:       400,
      textAlign:        'center',
      textOverflow:     'ellipsis',
      cursor:           'pointer',
      WebkitTransition: 'all .2s',
      transition:       'all .2s',
    },
    labelStyle:               {
      WebkitFontSmoothing,
      fontSize:  10,
      textAlign: 'center',
      bottom:    2,
      left:      0,
      right:     0,
      position:  'absolute',
      color:     '#fff',
    },
    buttonStyle:              {
      animation:       animationButton,
      height:          30,
      width:           120,
      borderTop:       '1px solid #faa760',
      borderRight:     '1px solid #e16800',
      borderBottom:    '1px solid #e16800',
      borderLeft:      0,
      fontSize:        17,
      lineHeight:      '17px',
      margin:          0,
      borderRadius:    3,
      position:        'absolute',
      left:            0,
      top:             5,
      backgroundColor: '#fd8a27',
      color:           '#fff',
      outline:         'none',
      cursor:          'pointer',
      opacity:         1,
      zIndex:          99999,
    },
    downloadButtonStyle:      {
      height:          20,
      width:           140,
      border:          '1px solid #ffffff',
      fontSize:        12,
      lineHeight:      '12px',
      margin:          0,
      borderRadius:    3,
      position:        'absolute',
      right:           0,
      top:             10,
      backgroundColor: 'transparent',
      color:           '#ffffff',
      outline:         'none',
      cursor:          'pointer',
      opacity:         0.9,
      textAlign:       'center',
    },
    bigLoadingStyle:          {
      display:         isLoading || !isLoaded ? 'block' : 'none',
      position:        'absolute',
      top:             67,
      left:            0,
      right:           0,
      bottom:          0,
      zIndex:          10000,
      backgroundColor: '#ccc',
    },
    bigLoadingHeadlineStyle:  {
      WebkitFontSmoothing,
      position:        'absolute',
      top:             '50%',
      left:            0,
      right:           0,
      WebkitTransform: 'translateY(-50%)',
      transform:       'translateY(-50%)',
      fontSize:        50,
      textAlign:       'center',
      color:           '#f0f0f0',
      textTransform:   'uppercase',
      margin:          '0',
    },
  };
};
