export const FETCH_STATISTICS_REQUEST = 'STATISTICS.FETCH_REQUEST';
export const FETCH_STATISTICS_SUCCESS = 'STATISTICS.FETCH_SUCCESS';
export const FETCH_STATISTICS_FAILURE = 'STATISTICS.FETCH_FAILURE';
