export default {
  pathToImages:   'build/amcharts/images/',
  type:           'serial',
  categoryField:  'date',
  dataDateFormat: 'YYYY-MM-DD HH',
  theme:          'default',
  categoryAxis:   {
    minPeriod:  'hh',
    parseDates: true,
  },
  chartCursor:    {
    enabled:                   true,
    categoryBalloonDateFormat: 'JJ:NN',
  },
  chartScrollbar: {
    enabled: true,
  },
  trendLines:     [],
  graphs:         [
    {
      bullet:     'round',
      id:         'AmGraph-1',
      title:      'Searches',
      valueField: 'searches',
      hidden:     true,
    },
    {
      bullet:     'round',
      id:         'AmGraph-2',
      title:      'Clicks',
      valueField: 'clicks',
    },
    {
      bullet:     'round',
      id:         'AmGraph-3',
      title:      'Uniq. clicks',
      valueField: 'unique_clicks',
    },
    {
      bullet:     'round',
      id:         'AmGraph-4',
      title:      'CTR',
      valueField: 'ctr',
      hidden:     true,
    },
    {
      bullet:     'round',
      id:         'AmGraph-5',
      title:      'Bookings',
      valueField: 'bookings',
      hidden:     true,
    },
    {
      bullet:     'round',
      id:         'AmGraph-6',
      title:      'Sales',
      valueField: 'sales',
      hidden:     true,
    },
    {
      bullet:     'round',
      id:         'AmGraph-7',
      title:      'BTR',
      valueField: 'btr',
      hidden:     true,
    },
    {
      bullet:     'round',
      id:         'AmGraph-8',
      title:      'STR',
      valueField: 'str',
      hidden:     true,
    },
    {
      bullet:     'round',
      id:         'AmGraph-9',
      title:      'Success',
      valueField: 'success',
      hidden:     true,
    },
    {
      bullet:     'round',
      id:         'AmGraph-10',
      title:      'Errors',
      valueField: 'errors',
      hidden:     true,
    },
    {
      bullet:     'round',
      id:         'AmGraph-11',
      title:      'Zeros',
      valueField: 'zeros',
      hidden:     true,
    },
    {
      bullet:     'round',
      id:         'AmGraph-12',
      title:      'T/O',
      valueField: 'timeouts',
      hidden:     true,
    },
    {
      bullet:     'round',
      id:         'AmGraph-13',
      title:      'Avg Resp',
      valueField: 'duration',
      hidden:     true,
    },
  ],
  guides:         [],
  valueAxes:      [
    {
      id:    'ValueAxis-1',
      title: 'Axis title',
    },
  ],
  allLabels:      [],
  balloon:        {},
  legend:         {
    enabled:          true,
    useGraphSettings: true,
  },
  titles:         [
    {
      id:   'Title-1',
      size: 15,
      text: 'Chart',
    },
  ],
};
