export const FETCH_USERS_REQUEST = 'USERS.FETCH_REQUEST';
export const FETCH_USERS_SUCCESS = 'USERS.FETCH_SUCCESS';
export const FETCH_USERS_FAILURE = 'USERS.FETCH_FAILURE';

export const NEXT_USERS_REQUEST = 'USERS.NEXT_REQUEST';
export const NEXT_USERS_SUCCESS = 'USERS.NEXT_SUCCESS';
export const NEXT_USERS_FAILURE = 'USERS.NEXT_FAILURE';
